spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/awm?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 30000
      query-timeout: 10
      validation-query: SELECT 1
      use-global-data-source-stat: true
      # 默认开启，当前已开启
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
      # 默认关闭，需手动开启，当前已开启
      slf4j:
        enabled: true
        data-source-log-enabled: false
        connection-log-enabled: false
        statement-log-enabled: false
        result-set-log-enabled: false
      # 默认关闭，需手动开启，当前已开启
      wall:
        enabled: true
        log-violation: true
        throw-exception: false
        config:
          delete-where-none-check: true
      # 默认关闭，需手动开启，当前已关闭
      config:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      web-stat:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      aop-stat:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      stat-view-servlet:
        enabled: false

  resources:
    static-locations: classpath:classpath:/resources/,classpath:/static/,file:${upload.image.path}
mybatis:
  mapper-locations: classpath:mappers/*.xml
debug: true
logging:
  level:
    pers.robin.awm.dao: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  offset-as-page-num: true
upload:
  #图片上传
  image:
    path: image/
    max-size: 2  #单位MB
    accept-type:
      - image/png
      - image/jpeg
      - image/jpg
server:
  ssl:
    key-store: keystore.p12
    key-store-password: qwer123
    key-store-type: PKCS12
    key-alias: tomcat
  port: 443

http-port: 8080
